### PR TITLE
Add scala service base

### PR DESCRIPTION
**Pull request by kenoir**
Remove unused fluentbit, nginx dockerfiles.

Adds simplified `scala_service_base` intended to replace`typesafe_config_base`.

### CODE REVIEW

**Comment by kenoir** [comment]
> Something I have wondered about before - how come we don't build our SBT apps in the Dockerfile, but rather COPY in the externally built target dir?

I think it didn't work very well and was difficult to understand.

**Comment by alexwlchan** [comment]
> how come we don't build our SBT apps in the Dockerfile, but rather COPY in the externally built target dir?

I think this would cause the compilation to happen entirely inside the Docker filesystem, which means we'd have to rebuild from fresh every time if running locally, no?

**Comment by kenoir** [comment]
> how come we don't build our SBT apps in the Dockerfile, but rather COPY in the externally built target dir?

We definitely tried it and abandoned it at some point.

> I think this would cause the compilation to happen entirely inside the Docker filesystem, which means we'd have to rebuild from fresh every time if running locally, no?

I can't remember.

**Comment by kenoir** [comment]
Closing as won't fix.

**Pull request closed without merging**
